CREATE TEMPORARY TABLE pa_flash_cat 
            (platform_action VARCHAR 
            , flash_report_category VARCHAR)
;
INSERT INTO pa_flash_cat 
	(platform_action, flash_report_category)
	VALUES
	('Accepted User Connection','Connect')
	, ('Account Created','Uncategorized')
	, ('Added Champion Analytics Widget','Other actions')
	, ('Added Champion Assessment Analytics Widget','Other actions')
	, ('Added Champion Cohort Overview Widget','Other actions')
	, ('Added Champion Program Analytics Widget','Other actions')
	, ('Added Collection to Queue','Uncategorized')
	, ('Added Moment to Queue','Uncategorized')
	, ('Added To-Do Item from Content','To-do')
	, ('Added Tree to Queue','Uncategorized')
	, ('Added User Program Progress Widget','Other actions')
	, ('Added User Space Widget','Other actions')
	, ('Answered Assessment Item','Consume')
	, ('Assigned To-Do Item','To-do')
	, ('Became Champion Member','Other actions')
	, ('Became Organization Member','Other actions')
	, ('Champion Membership Invitation Accepted','Other actions')
	, ('Champion Membership Invitation Declined','Other actions')
	, ('Clicked Button on Page','Consume')
	, ('Clicked Collection Card on Page','Consume')
	, ('Clicked External Link Card on Page','Consume')
	, ('Clicked Moment Card on Page','Consume')
	, ('Clicked Page Card on Page','Consume')
	, ('Clicked Program Card on Page','Consume')
	, ('Clicked Social Icon on Page','Consume')
	, ('Cloned Program','Uncategorized')
	, ('Commented on Group Space Post','Space')
	, ('Commented on Private Space Post','Space')
	, ('Commented on Shared Space Post','Space')
	, ('Commented on Timeline Post','Feed')
	, ('Commented on Unactivated Space Post','Space')
	, ('Completed To-Do Item','To-do')
	, ('Connected to Champion','Connect')
	, ('Created AddToQueueElement Element','Uncategorized')
	, ('Created AssessmentMetricPrerequisite Prerequisite','Uncategorized')
	, ('Created AssessmentResultPrerequisite Prerequisite','Uncategorized')
	, ('Created BlockquoteElement Element','Uncategorized')
	, ('Created ChampionConnectElement Element','Uncategorized')
	, ('Created CohortConnectElement Element','Uncategorized')
	, ('Created ConfigureChampionDashboardElement Element','Uncategorized')
	, ('Created ConfigureUserDashboardElement Element','Uncategorized')
	, ('Created ContentNode Node','Uncategorized')
	, ('Created CreateSpaceElement Element','Uncategorized')
	, ('Created DisplayChildrenElement Element','Uncategorized')
	, ('Created EparachuteElement Element','Uncategorized')
	, ('Created FileListElement Element','Uncategorized')
	, ('Created FormElement Element','Uncategorized')
	, ('Created FormReferenceElement Element','Uncategorized')
	, ('Created Group Space','Create')
	, ('Created HeaderElement Element','Uncategorized')
	, ('Created HorizontalRuleElement Element','Uncategorized')
	, ('Created ImageElement Element','Uncategorized')
	, ('Created IntervalSinceStartPrerequisite Prerequisite','Uncategorized')
	, ('Created JoinGroupSpaceElement Element','Uncategorized')
	, ('Created LandingPageElement Element','Uncategorized')
	, ('Created ListElement Element','Uncategorized')
	, ('Created MomentElement Element','Uncategorized')
	, ('Created Note in Content','Create')
	, ('Created OnboardingElement Element','Uncategorized')
	, ('Created ParagraphElement Element','Uncategorized')
	, ('Created PlatformLinkElement Element','Uncategorized')
	, ('Created Private Collection','Create')
	, ('Created Private Moment','Create')
	, ('Created Private Space','Create')
	, ('Created Program','Create')
	, ('Created Public Collection','Create')
	, ('Created Public Moment','Create')
	, ('Created QuestionElement Element','Uncategorized')
	, ('Created QuizElement Element','Uncategorized')
	, ('Created ReferenceNode Node','Uncategorized')
	, ('Created ResourceListElement Element','Uncategorized')
	, ('Created ResultElement Element','Uncategorized')
	, ('Created Shared Space','Create')
	, ('Created SoundcloudElement Element','Uncategorized')
	, ('Created ToDoListElement Element','Uncategorized')
	, ('Created Unactivated Space','Uncategorized')
	, ('Created UnlockDatePrerequisite Prerequisite','Uncategorized')
	, ('Created UserImageElement Element','Uncategorized')
	, ('Created UserNoteElement Element','Uncategorized')
	, ('Created VideoElement Element','Uncategorized')
	, ('Created VideoListElement Element','Uncategorized')
	, ('Created VideoPlaylistElement Element','Uncategorized')
	, ('Created WebLinkElement Element','Uncategorized')
	, ('Created a New Dashboard','Uncategorized')
	, ('Deleted Element','Uncategorized')
	, ('Deleted Node','Uncategorized')
	, ('Deleted Prerequisite','Uncategorized')
	, ('Deleted Program','Uncategorized')
	, ('Deleted To-Do Item','To-do')
	, ('FamilyLife - Clicked Donate Button','Consume')
	, ('FamilyLife - Clicked Resource Link','Consume')
	, ('FamilyLife - Listened to Broadcast','Consume')
	, ('Followed Champion','Uncategorized')
	, ('Followed User','Connect')
	, ('Invited User To Group Space','Invite')
	, ('Invited User To Private Space','Invite')
	, ('Invited User To Shared Space','Invite')
	, ('Invited User To Unactivated Space','Uncategorized')
	, ('Joined Group Space','Space')
	, ('Joined Private Space','Space')
	, ('Joined Shared Space','Space')
	, ('Joined Unactivated Space','Space')
	, ('Left Group Space','Space')
	, ('Left Private Space','Space')
	, ('Left Shared Space','Space')
	, ('Left Unactivated Space','Space')
	, ('Listened to Broadcast on Page','Consume')
	, ('Made Collection Private','Create')
	, ('Made Collection Public','Create')
	, ('Made Moment Private','Create')
	, ('Made Moment Public','Create')
	, ('Post to Timeline','Feed')
	, ('Posted to Group Space','Space')
	, ('Posted to Private Space','Space')
	, ('Posted to Shared Space','Space')
	, ('Progressed Through Content','Consume')
	, ('Rated Champion','Other actions')
	, ('Rated Program','Other actions')
	, ('Requested User Connection','Connect')
	, ('Sent Tree Invitation','Invite')
	, ('Shared Champion to Group Space','Space')
	, ('Shared Champion to Shared Space','Space')
	, ('Shared Collection to Group Space','Space')
	, ('Shared Collection to Private Space','Space')
	, ('Shared Collection to Shared Space','Space')
	, ('Shared Collection to Timeline','Feed')
	, ('Shared Form Response to Group Space','Space')
	, ('Shared Form Response to Private Space','Space')
	, ('Shared Form Response to Shared Space','Space')
	, ('Shared Form Response to Timeline','Feed')
	, ('Shared LandingPage to Group Space','Space')
	, ('Shared LandingPage to Private Space','Space')
	, ('Shared LandingPage to Shared Space','Space')
	, ('Shared LandingPage to Timeline','Feed')
	, ('Shared Link to Group Space','Space')
	, ('Shared Link to Private Space','Space')
	, ('Shared Link to Shared Space','Space')
	, ('Shared Link to Timeline','Feed')
	, ('Shared Media to Group Space','Space')
	, ('Shared Media to Private Space','Space')
	, ('Shared Media to Shared Space','Space')
	, ('Shared Media to Timeline','Feed')
	, ('Shared Moment to Group Space','Space')
	, ('Shared Moment to Private Space','Space')
	, ('Shared Moment to Shared Space','Space')
	, ('Shared Moment to Timeline','Feed')
	, ('Shared Note to Group Space','Space')
	, ('Shared Note to Private Space','Space')
	, ('Shared Note to Shared Space','Space')
	, ('Shared Note to Timeline','Feed')
	, ('Shared Post to Group Space','Space')
	, ('Shared Post to Private Space','Space')
	, ('Shared Post to Shared Space','Space')
	, ('Shared Post to Timeline','Feed')
	, ('Shared Program to Group Space','Space')
	, ('Shared Program to Private Space','Space')
	, ('Shared Program to Shared Space','Space')
	, ('Shared Program to Timeline','Feed')
	, ('Shared Result to Group Space','Space')
	, ('Shared Result to Private Space','Space')
	, ('Shared Result to Shared Space','Space')
	, ('Shared Result to Timeline','Feed')
	, ('Space Membership Invitation Accepted','Space')
	, ('Space Membership Invitation Declined','Space')
	, ('Started Content','Consume')
	, ('Started Moment','Consume')
	, ('Started Session','Uncategorized')
	, ('Unpublished Program','Uncategorized')
	, ('Updated Node','Uncategorized')
	, ('Updated Prerequisite','Uncategorized')
	, ('Updated AddToQueueElement Element','Uncategorized')
	, ('Updated AssessmentMetricPrerequisite Prerequisite','Uncategorized')
	, ('Updated AssessmentResultPrerequisite Prerequisite','Uncategorized')
	, ('Updated BlockquoteElement Element','Uncategorized')
	, ('Updated ChampionConnectElement Element','Uncategorized')
	, ('Updated CohortConnectElement Element','Uncategorized')
	, ('Updated ContentNode Node','Uncategorized')
	, ('Updated CreateSpaceElement Element','Uncategorized')
	, ('Updated DisplayChildrenElement Element','Uncategorized')
	, ('Updated EparachuteElement Element','Uncategorized')
	, ('Updated FormElement Element','Uncategorized')
	, ('Updated FormReferenceElement Element','Uncategorized')
	, ('Updated HeaderElement Element','Uncategorized')
	, ('Updated HorizontalRuleElement Element','Uncategorized')
	, ('Updated ImageElement Element','Uncategorized')
	, ('Updated IntervalSinceStartPrerequisite Prerequisite','Uncategorized')
	, ('Updated JoinGroupSpaceElement Element','Uncategorized')
	, ('Updated LandingPageElement Element','Uncategorized')
	, ('Updated ListElement Element','Uncategorized')
	, ('Updated MomentElement Element','Uncategorized')
	, ('Updated OnboardingElement Element','Uncategorized')
	, ('Updated ParagraphElement Element','Uncategorized')
	, ('Updated PlatformLinkElement Element','Uncategorized')
	, ('Updated Program','Uncategorized')
	, ('Updated QuestionElement Element','Uncategorized')
	, ('Updated QuizElement Element','Uncategorized')
	, ('Updated ReferenceNode Node','Uncategorized')
	, ('Updated ResourceListElement Element','Uncategorized')
	, ('Updated ResultElement Element','Uncategorized')
	, ('Updated SoundcloudElement Element','Uncategorized')
	, ('Updated ToDoListElement Element','Uncategorized')
	, ('Updated UnlockDatePrerequisite Prerequisite','Uncategorized')
	, ('Updated UserImageElement Element','Uncategorized')
	, ('Updated UserNoteElement Element','Uncategorized')
	, ('Updated VideoElement Element','Uncategorized')
	, ('Updated VideoPlaylistElement Element','Uncategorized')
	, ('Updated WebLinkElement Element','Uncategorized')
	, ('User Added Page','Consume')
	, ('User Onboarded','Invite')
	, ('User Removed Page','Consume')
;
